Issue #9 Mark an item as purchased
the-collab-lab/tcl-70-smart-shopping-list pull request #29
Opened 2024-02-28 22:05 UTC by amandaguan-ag

## Description

Add checkbox to allow user to mark the their items as purchased and remain purchased for 24 hours. The checkbox will unclick itself after 24 hours.
## Related Issue

close #9 
## Acceptance Criteria
- [x] The `ListItem` component renders a checkbox with a semantic `<label>`.
- [x] Checking off the item in the UI also updates the `dateLastPurchased` and `totalPurchases` properties on the corresponding Firestore document
- [x] The item is shown as checked for 24 hours after the purchase is made (i.e. we assume the user does not need to buy the item again for at least 1 day). After 24 hours, the item unchecks itself so the user can buy it again.
- [x] The `updateItem` function in `firebase.js` has been filled out, and sends updates to the firestore database when an item is checked

## Type of Changes

enhancement

## Updates

### Before

<img width="1141" alt="image" src="https://github.com/the-collab-lab/tcl-70-smart-shopping-list/assets/121919044/bc24fa83-c4cb-49c9-9398-0f2f04c4589d">

### After

<img width="1141" alt="image" src="https://github.com/the-collab-lab/tcl-70-smart-shopping-list/assets/121919044/30316621-8f1c-4df2-9502-f91ab206be13">

## Testing Steps / QA Criteria
- From your terminal, pull down this branch with `git pull origin ag-lc-mark-as-purchase` and check out with `git checkout ag-lc-mark-as-purchase`
- Then enter `npm start`
- Click an item in List view, the dateLastPurchase should be updated with the time you click
- Go to firstore to change the dateLastPurchase to a date that is pasted within 24 hours (eg feb 28th 1pm -> feb 27th 10pm) the dateLastPurchase is , the item should be remained clicked
- Go to firstore to change the dateLastPurchase to a date that past over 24 hours(eg feb 28th 1pm -> feb 1st 1pm) , the item should be automatically unclicked

2024-02-29 08:12 UTC, g-lee2 reviewed
Hey! Nice work! So the site breaks when there are items in a shopping list that are missing a dateLastPurchased because of the dateLastPurchased.seconds dependency in the useEffect. Using dateLastPurchased instead fixes this. Also, considering the 24-hour checkbox disable logic, the else statement in handleChange seems redundant.

2024-03-01 15:03 UTC, MiliMade commented on src/components/ListItem.jsx
Just echoing a what @g-lee2 said earlier about the useEffect dependency on line 35 - I'm getting a blank screen in the list view. Once I changed ```dateLastPurchased.seconds``` to just ```dateLastPurchased```, everything seemed to work. I was able to see the list items and the empty checkboxes next to them.  Clicking the box gives me a prompt to confirm purchase and the box is then checked and greyed out.

2024-03-01 15:06 UTC, MiliMade requested changes
Might need to change the dependency on useEffect

2024-03-01 18:09 UTC, chungleee commented on src/components/ListItem.jsx
nice catch! 

edited to `dateLastPurchased` and removed the `else` in `handleChange`

2024-03-01 18:47 UTC, g-lee2 approved these changes

2024-03-01 21:20 UTC, MiliMade approved these changes

2024-03-01 21:21 UTC, MiliMade approved these changes

2024-03-01 23:12 UTC, djtaylor8 approved these changes
Really nice job on this! Left a minor comment about adding missing items to a dependency array, but otherwise this is looking good. 

I would also recommend adding in a few more comments to your code to provide some more clarity. You don't need to add much, but they can help clarify things in the future and also it's good documentation practice.

2024-03-01 23:12 UTC, djtaylor8 commented on src/components/ListItem.jsx
> +	const handleChange = async () => {
Nice implementation here! I know this isn't explicitly in the AC, but I think this provides a better user experience to make sure a user doesn't accidentally check something.

2024-03-01 23:12 UTC, djtaylor8 commented on src/components/ListItem.jsx
> +	}, [isChecked]);
I'm seeing a few missing dependencies from this array:

<img width="879" alt="Screenshot 2024-03-01 at 3 04 39 PM" src="https://github.com/the-collab-lab/tcl-70-smart-shopping-list/assets/78327387/b479ef93-3730-43fc-89ca-252cea181056">

2024-03-02 16:25 UTC, lyleschemmerling approved these changes
Tested and looks like it's work working great. Good job!

2024-03-02 16:25 UTC, lyleschemmerling commented on src/api/firebase.js
>  	 * TODO: Fill this out so that it uses the correct Firestore function
We should take out the TODO now that we filled in the function definition

2024-03-02 22:06 UTC, RachaelSkye approved these changes
Great work!

2024-03-03 18:09 UTC, merged